### ISSUE TITLE
Map: No longer showing location of entries

### ISSUE THREAD

**Issue by jdelamere** [gina-alaska/gina-catalog#726]
- Map is blank.
- log shows...
  ActionView::Template::Error (undefined method `entry_url' for #<#Class:0x007fb24954d8c0:0x007fb248e057e8>):
   8:         json.properties do
   9:           json.index ''
  10:           json.id dom_id(entry)
  11:           json.url entry_url(entry)
  12:           json.title entry.title
  13:           json.description entry.description.truncate(200)
  14:           json.set! 'marker-color', entry.entry_type.color
- Probably introduced in pull request #720
